################################################################################
#                                                                              #
#                       NEVER INCLUDE SECRET.YML IN GITHUB                     #
#                                                                              #
#                         If you do change all secrets                         #
#                                                                              #
################################################################################
#
# secrets.example.yml
#
#   - This file is a template for secret.yml
#   - secret.yml holds unique identifiers that allow a user to take over an
#     application.
#
#  - 1 cp secrets.example.yml secrets.yml
#  - 2 run 'rake secret' for each environment
#  - 3 Replace 'RUN_RAKE_SECRET_AND_PASTE_OVER_THIS' with the generated numbers
#  - 4 Restart your server after modifying
#
#
# Secret.yml must be available in production or the application won't run
#  - Capistrano is responsible for copying the secret.yml over
#
#
development:
  HOST: localhost:1025
  DOMAIN: 'development.example.com'
  secret_key_base: 04fdc051def49298391b91a5450241c4a697e707d7bd9e6861b28e8cd1dd2811509e903f856b0dd4722a78e15221447efed6ed80b27862dba3c132f12596c85e

# Required by travis - you can encrypt it, see link, but instead I prefer to
# only use the secret here and here alone!
# http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
#
test:
  HOST: localhost:1025
  DOMAIN: 'test.example.com'
  secret_key_base: fcc110bf862fd98999dc0c011438f4362796e7e795ad6678d83c6eca248a5b0c571bee49d03c1e8442c7739ce89a681dcd9d470f48ace4cd34115a8c0719aa76

staging:
  HOST: 'www.my-domain.com'
  DOMAIN: "my-domain.com"
  SMTP_ADDRESS: 'smtp.organisation.org'
  SMTP_PORT: 587
  EMAIL_USERNAME: Enter Username
  EMAIL_PASSWORD: Enter Password
  secret_key_base: RUN_RAKE_SECRET_AND_PASTE_OVER_THIS

production:
  HOST: 'www.my-domain.com'
  DOMAIN: "my-domain.com"
  SMTP_ADDRESS: 'smtp.organisation.org'
  SMTP_PORT: 587
  EMAIL_USERNAME: Enter Username
  EMAIL_PASSWORD: Enter Password
  secret_key_base: RUN_RAKE_SECRET_AND_PASTE_OVER_THIS
