#
# Copy the file to secrets.yml
#   - add secret to production secret_key_base
#
# Configurations required to run the application
# Do not check into open repository like github.
#
development:
  HOST: localhost:1025
  DOMAIN: 'development.example.com'
  secret_key_base: 04fdc051def49298391b91a5450241c4a697e707d7bd9e6861b28e8cd1dd2811509e903f856b0dd4722a78e15221447efed6ed80b27862dba3c132f12596c85e

test:
  HOST: localhost:1025
  DOMAIN: 'test.example.com'
  secret_key_base: fcc110bf862fd98999dc0c011438f4362796e7e795ad6678d83c6eca248a5b0c571bee49d03c1e8442c7739ce89a681dcd9d470f48ace4cd34115a8c0719aa76

production:
  HOST: 'www.my-domain.com'
  DOMAIN: "my-domain.com"
  SMTP_ADDRESS: 'smtp.organisation.org'
  SMTP_PORT: 587
  EMAIL_USERNAME: Enter Username
  EMAIL_PASSWORD: Enter Password
  secret_key_base: #_Run_rake_secret_and_copy_over_this
